// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

public enum Header : sbyte
{
 EXCEPT = 0,
 PLAYER_REQ = 1,
 PLAYER_RES = 2,
 GAME_STATE = 3,
 MOVE = 4,
 ROTATE = 5,
 SHOOT = 6,
 ACHE = 7,
 RECALL = 8,
 DIE = 9,
 RESPAWN = 10,
 GAME_RESULT = 11,
 HEARTBEAT = 12,
 WATCH_REQ = 13,
 PLAYER_OUT = 14,
};


}
