// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

using System;
using FlatBuffers;

public struct HeartBeat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static HeartBeat GetRootAsHeartBeat(ByteBuffer _bb) { return GetRootAsHeartBeat(_bb, new HeartBeat()); }
  public static HeartBeat GetRootAsHeartBeat(ByteBuffer _bb, HeartBeat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public HeartBeat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public bool Live { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<HeartBeat> CreateHeartBeat(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      bool Live = false) {
    builder.StartObject(2);
    HeartBeat.AddName(builder, nameOffset);
    HeartBeat.AddLive(builder, Live);
    return HeartBeat.EndHeartBeat(builder);
  }

  public static void StartHeartBeat(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddLive(FlatBufferBuilder builder, bool Live) { builder.AddBool(1, Live, false); }
  public static Offset<HeartBeat> EndHeartBeat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HeartBeat>(o);
  }
};


}
