// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

using System;
using FlatBuffers;

public struct Vec2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float R { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float Rotate { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<Vec2> CreateVec2(FlatBufferBuilder builder, float X, float Z, float R, float Rotate) {
    builder.Prep(4, 16);
    builder.PutFloat(Rotate);
    builder.PutFloat(R);
    builder.PutFloat(Z);
    builder.PutFloat(X);
    return new Offset<Vec2>(builder.Offset);
  }
};


}
