// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

using System;
using FlatBuffers;

public struct Vec5 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec5 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float R { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }
  public float Horizontal { get { return __p.bb.GetFloat(__p.bb_pos + 16); } }
  public float Vertical { get { return __p.bb.GetFloat(__p.bb_pos + 20); } }

  public static Offset<Vec5> CreateVec5(FlatBufferBuilder builder, float X, float Y, float Z, float R, float Horizontal, float Vertical) {
    builder.Prep(4, 24);
    builder.PutFloat(Vertical);
    builder.PutFloat(Horizontal);
    builder.PutFloat(R);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<Vec5>(builder.Offset);
  }
};


}
