// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

using System;
using FlatBuffers;

public struct Watch : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Watch GetRootAsWatch(ByteBuffer _bb) { return GetRootAsWatch(_bb, new Watch()); }
  public static Watch GetRootAsWatch(ByteBuffer _bb, Watch obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Watch __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Roomid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Watch> CreateWatch(FlatBufferBuilder builder,
      int roomid = 0) {
    builder.StartObject(1);
    Watch.AddRoomid(builder, roomid);
    return Watch.EndWatch(builder);
  }

  public static void StartWatch(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRoomid(FlatBufferBuilder builder, int roomid) { builder.AddInt(0, roomid, 0); }
  public static Offset<Watch> EndWatch(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Watch>(o);
  }
};


}
