// automatically generated by the FlatBuffers compiler, do not modify

namespace Protocol
{

public enum WepId : int
{
 None = 0,
 rifle = 1,
 yutan = 2,
 samurai = 3,
 rifle_up = 4,
 yutan_up = 5,
 samurai_up = 6,
};


}
