using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public enum EVENT_TYPE{PLAYER_CONNECT,PLAYER_MOVE,PLAYER_ROTATE, PLAYER_FIRE, PLAYER_WOUND ,PLAYER_DEAD, PLAYER_OUT,
	R_PLAYER_MOVE, R_PLAYER_ROTATE,R_PLAYER_FIRE, R_PLAYER_WOUND, R_PLAYER_RECALL ,R_PLAYER_DEAD, R_PLAYER_RESPAWN,
	NETWORK_LOGIN, NETWORK_ROOMLIST, LOBBY_LOGIN, LOBBY_ROOMLIST,NETWORK_ROOM_JOIN, NETWORK_GAME_END,
	GAMEMANAGER_CONNECT, GAME_READY, GAME_START, GAME_END, GAME_RESULT, CHAT_MSG};

public interface IListener {

	void OnEvent(EVENT_TYPE Evenet_Type, Component Sender, object Parm = null);

}
